[relaychain]
default_image = "parity/polkadot:latest"
default_command = "polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  args = ["-lparachain::collator-protocol=trace,parachain::candidate-validation=trace,parachain::pvf=trace"]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  args = ["-lparachain::collator-protocol=trace,parachain::candidate-validation=trace,parachain::pvf=trace"]

[[parachains]]
id = 2000
cumulus_based = true
chain = "asset-hub-rococo-local"

  # run charlie as parachain collator
  [[parachains.collators]]
  name = "charlie"
  validator = true
  image = "parity/polkadot-parachain:latest"
  command = "polkadot-parachain"
  args = ["--force-authoring", "--experimental-use-slot-based", "-lparachain::collator-protocol=trace,parachain::candidate-validation=trace,aura=trace"]
